package com.guide.green.green_guide_master.Utilities;

import android.support.annotation.NonNull;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class RomanizedLocation implements Comparable<RomanizedLocation> {
    public final String name;
    public final String pinyin;
    public final String fullName;

    public RomanizedLocation(String name, String pinyin) {
        this(name, pinyin, null);
    }

    public RomanizedLocation(String name, String pinyin, String fullName) {
        this.name = name;
        this.pinyin = pinyin;
        this.fullName = fullName;
    }
    @Override
    public String toString() {
        return pinyin;
    }

    @Override
    public int compareTo(@NonNull RomanizedLocation romanizedLocation) {
        return pinyin.compareTo(romanizedLocation.pinyin);
    }

    private static List<RomanizedLocation> province;
    public static List<RomanizedLocation> getProvinces() {
        if (province == null) {
            province = new ArrayList<RomanizedLocation>();
            province.add(new RomanizedLocation("安徽", "anhui"));
            province.add(new RomanizedLocation("福建", "fujian"));
            province.add(new RomanizedLocation("甘肃", "gansu"));
            province.add(new RomanizedLocation("广东", "guangdong"));
            province.add(new RomanizedLocation("广西", "guangxi"));
            province.add(new RomanizedLocation("贵州", "guizhou"));
            province.add(new RomanizedLocation("海南", "hainan"));
            province.add(new RomanizedLocation("河北", "hebei"));
            province.add(new RomanizedLocation("河南", "henan"));
            province.add(new RomanizedLocation("黑龙江", "heilongjiang"));
            province.add(new RomanizedLocation("湖北", "hubei"));
            province.add(new RomanizedLocation("湖南", "hunan"));
            province.add(new RomanizedLocation("江苏", "jiangsu"));
            province.add(new RomanizedLocation("江西", "jiangxi"));
            province.add(new RomanizedLocation("吉林", "jilin", "吉林省"));
            province.add(new RomanizedLocation("辽宁", "liaoning"));
            province.add(new RomanizedLocation("内蒙古", "neimenggu"));
            province.add(new RomanizedLocation("宁夏", "ningxia"));
            province.add(new RomanizedLocation("青海", "qinghai"));
            province.add(new RomanizedLocation("山东", "shandong"));
            province.add(new RomanizedLocation("山西", "shanxi"));
            province.add(new RomanizedLocation("陕西", "shanxi"));
            province.add(new RomanizedLocation("四川", "sichuan"));
            province.add(new RomanizedLocation("西藏", "xizang"));
            province.add(new RomanizedLocation("新疆", "xinjiang"));
            province.add(new RomanizedLocation("云南", "yunnan"));
            province.add(new RomanizedLocation("浙江", "zhejiang"));
            province.add(new RomanizedLocation("台湾", "taiwan"));
            Collections.sort(province);
        }
        return new ArrayList<>(province);
    }

    private static List<RomanizedLocation> cities;
    public static List<RomanizedLocation> getCities() {
        if (cities == null) {
            cities = new ArrayList<RomanizedLocation>();
            cities.add(new RomanizedLocation("合肥", "hefei"));
            cities.add(new RomanizedLocation("安庆", "anqing"));
            cities.add(new RomanizedLocation("蚌埠", "bangbu"));
            cities.add(new RomanizedLocation("亳州", "bozhou"));
            cities.add(new RomanizedLocation("巢湖", "chaohu"));
            cities.add(new RomanizedLocation("池州", "chizhou"));
            cities.add(new RomanizedLocation("滁州", "chuzhou"));
            cities.add(new RomanizedLocation("阜阳", "fuyang"));
            cities.add(new RomanizedLocation("淮北", "huaibei"));
            cities.add(new RomanizedLocation("淮南", "huainan"));
            cities.add(new RomanizedLocation("黄山", "huangshan"));
            cities.add(new RomanizedLocation("六安", "liuan"));
            cities.add(new RomanizedLocation("马鞍山", "maanshan"));
            cities.add(new RomanizedLocation("宿州", "suzhou"));
            cities.add(new RomanizedLocation("铜陵", "tongling"));
            cities.add(new RomanizedLocation("芜湖", "wuhu"));
            cities.add(new RomanizedLocation("宣城", "xuancheng"));
            cities.add(new RomanizedLocation("福州", "fuzhou"));
            cities.add(new RomanizedLocation("龙岩", "longyan"));
            cities.add(new RomanizedLocation("南平", "nanping"));
            cities.add(new RomanizedLocation("宁德", "ningde"));
            cities.add(new RomanizedLocation("莆田", "putian"));
            cities.add(new RomanizedLocation("泉州", "quanzhou"));
            cities.add(new RomanizedLocation("三明", "sanming"));
            cities.add(new RomanizedLocation("厦门", "xiamen"));
            cities.add(new RomanizedLocation("漳州", "zhangzhou"));
            cities.add(new RomanizedLocation("兰州", "lanzhou"));
            cities.add(new RomanizedLocation("白银", "baiyin"));
            cities.add(new RomanizedLocation("定西", "dingxi"));
            cities.add(new RomanizedLocation("甘南州", "gannanzhou", "甘南藏族自治州"));
            cities.add(new RomanizedLocation("嘉峪关", "jiayuguan"));
            cities.add(new RomanizedLocation("金昌", "jinchang"));
            cities.add(new RomanizedLocation("酒泉", "jiuquan"));
            cities.add(new RomanizedLocation("临夏州", "linxiazhou", "临夏回族自治州"));
            cities.add(new RomanizedLocation("陇南", "longnan"));
            cities.add(new RomanizedLocation("平凉", "pingliang"));
            cities.add(new RomanizedLocation("庆阳", "qingyang"));
            cities.add(new RomanizedLocation("天水", "tianshui"));
            cities.add(new RomanizedLocation("武威", "wuwei"));
            cities.add(new RomanizedLocation("张掖", "zhangye"));
            cities.add(new RomanizedLocation("广州", "guangzhou"));
            cities.add(new RomanizedLocation("潮州", "chaozhou"));
            cities.add(new RomanizedLocation("东莞", "dongguan"));
            cities.add(new RomanizedLocation("佛山", "foshan"));
            cities.add(new RomanizedLocation("河源", "heyuan"));
            cities.add(new RomanizedLocation("惠州", "huizhou"));
            cities.add(new RomanizedLocation("江门", "jiangmen"));
            cities.add(new RomanizedLocation("揭阳", "jieyang"));
            cities.add(new RomanizedLocation("茂名", "maoming"));
            cities.add(new RomanizedLocation("梅州", "meizhou"));
            cities.add(new RomanizedLocation("清远", "qingyuan"));
            cities.add(new RomanizedLocation("汕头", "shantou"));
            cities.add(new RomanizedLocation("汕尾", "shanwei"));
            cities.add(new RomanizedLocation("韶关", "shaoguan"));
            cities.add(new RomanizedLocation("深圳", "shenzhen"));
            cities.add(new RomanizedLocation("阳江", "yangjiang"));
            cities.add(new RomanizedLocation("云浮", "yunfu"));
            cities.add(new RomanizedLocation("湛江", "zhanjiang"));
            cities.add(new RomanizedLocation("肇庆", "zhaoqing"));
            cities.add(new RomanizedLocation("中山", "zhongshan"));
            cities.add(new RomanizedLocation("珠海", "zhuhai"));
            cities.add(new RomanizedLocation("南宁", "nanning"));
            cities.add(new RomanizedLocation("百色", "baise"));
            cities.add(new RomanizedLocation("北海", "beihai"));
            cities.add(new RomanizedLocation("崇左", "chongzuo"));
            cities.add(new RomanizedLocation("防城港", "fangchenggang"));
            cities.add(new RomanizedLocation("桂林", "guilin"));
            cities.add(new RomanizedLocation("贵港", "guigang"));
            cities.add(new RomanizedLocation("河池", "hechi"));
            cities.add(new RomanizedLocation("贺州", "hezhou"));
            cities.add(new RomanizedLocation("来宾", "laibin"));
            cities.add(new RomanizedLocation("柳州", "liuzhou"));
            cities.add(new RomanizedLocation("钦州", "qinzhou"));
            cities.add(new RomanizedLocation("梧州", "wuzhou"));
            cities.add(new RomanizedLocation("玉林", "yulin"));
            cities.add(new RomanizedLocation("贵阳", "guiyang"));
            cities.add(new RomanizedLocation("安顺", "anshun"));
            cities.add(new RomanizedLocation("毕节市", "bijie"));
            cities.add(new RomanizedLocation("六盘水", "liupanshui"));
            cities.add(new RomanizedLocation("铜仁市", "tongren"));
            cities.add(new RomanizedLocation("遵义", "zunyi"));
            cities.add(new RomanizedLocation("黔西南州", "qianxinanzhou", "黔西南布依族苗族自治州"));
            cities.add(new RomanizedLocation("黔东南州", "qiandongnanzhou", "黔东南苗族侗族自治州"));
            cities.add(new RomanizedLocation("黔南州", "qiannanzhou", "黔南布依族苗族自治州"));
            cities.add(new RomanizedLocation("海口", "haikou"));
            cities.add(new RomanizedLocation("白沙", "baisha", "白沙黎族自治县"));
            cities.add(new RomanizedLocation("保亭", "baoting", "保亭黎族苗族自治县"));
            cities.add(new RomanizedLocation("昌江", "changjiang", "昌江黎族自治县"));
            cities.add(new RomanizedLocation("儋州", "danzhou"));
            cities.add(new RomanizedLocation("澄迈", "chengmai"));
            cities.add(new RomanizedLocation("东方", "dongfang"));
            cities.add(new RomanizedLocation("定安", "dingan"));
            cities.add(new RomanizedLocation("琼海", "qionghai"));
            cities.add(new RomanizedLocation("琼中", "qiongzhong", "琼中黎族苗族自治县"));
            cities.add(new RomanizedLocation("乐东", "ledong", "乐东黎族自治县"));
            cities.add(new RomanizedLocation("临高", "lingao"));
            cities.add(new RomanizedLocation("陵水", "lingshui", "陵水黎族自治县"));
            cities.add(new RomanizedLocation("三亚", "sanya"));
            cities.add(new RomanizedLocation("屯昌", "tunchang"));
            cities.add(new RomanizedLocation("万宁", "wanning"));
            cities.add(new RomanizedLocation("文昌", "wenchang"));
            cities.add(new RomanizedLocation("五指山", "wuzhishan"));
            cities.add(new RomanizedLocation("石家庄", "shijiazhuang"));
            cities.add(new RomanizedLocation("保定", "baoding"));
            cities.add(new RomanizedLocation("沧州", "cangzhou"));
            cities.add(new RomanizedLocation("承德", "chengde"));
            cities.add(new RomanizedLocation("邯郸", "handan"));
            cities.add(new RomanizedLocation("衡水", "hengshui"));
            cities.add(new RomanizedLocation("廊坊", "langfang"));
            cities.add(new RomanizedLocation("秦皇岛", "qinhuangdao"));
            cities.add(new RomanizedLocation("唐山", "tangshan"));
            cities.add(new RomanizedLocation("邢台", "xingtai"));
            cities.add(new RomanizedLocation("张家口", "zhangjiakou"));
            cities.add(new RomanizedLocation("郑州", "zhengzhou"));
            cities.add(new RomanizedLocation("安阳", "anyang"));
            cities.add(new RomanizedLocation("鹤壁", "hebi"));
            cities.add(new RomanizedLocation("焦作", "jiaozuo"));
            cities.add(new RomanizedLocation("开封", "kaifeng"));
            cities.add(new RomanizedLocation("洛阳", "luoyang"));
            cities.add(new RomanizedLocation("漯河", "luohe"));
            cities.add(new RomanizedLocation("南阳", "nanyang"));
            cities.add(new RomanizedLocation("平顶山", "pingdingshan"));
            cities.add(new RomanizedLocation("濮阳", "puyang"));
            cities.add(new RomanizedLocation("三门峡", "sanmenxia"));
            cities.add(new RomanizedLocation("商丘", "shangqiu"));
            cities.add(new RomanizedLocation("新乡", "xinxiang"));
            cities.add(new RomanizedLocation("信阳", "xinyang"));
            cities.add(new RomanizedLocation("许昌", "xuchang"));
            cities.add(new RomanizedLocation("周口", "zhoukou"));
            cities.add(new RomanizedLocation("驻马店", "zhumadian"));
            cities.add(new RomanizedLocation("哈尔滨", "haerbin"));
            cities.add(new RomanizedLocation("大庆", "daqing"));
            cities.add(new RomanizedLocation("大兴安岭地区", "daxinganling"));
            cities.add(new RomanizedLocation("鹤岗", "hegang"));
            cities.add(new RomanizedLocation("黑河", "heihe"));
            cities.add(new RomanizedLocation("鸡西", "jixi"));
            cities.add(new RomanizedLocation("佳木斯", "jiamusi"));
            cities.add(new RomanizedLocation("牡丹江", "mudanjiang"));
            cities.add(new RomanizedLocation("七台河", "qitaihe"));
            cities.add(new RomanizedLocation("齐齐哈尔", "qiqihaer"));
            cities.add(new RomanizedLocation("双鸭山", "shuangyashan"));
            cities.add(new RomanizedLocation("绥化", "suihua"));
            cities.add(new RomanizedLocation("伊春", "yichun"));
            cities.add(new RomanizedLocation("武汉", "wuhan"));
            cities.add(new RomanizedLocation("鄂州", "ezhou"));
            cities.add(new RomanizedLocation("恩施", "enshi", "恩施土家族苗族自治州"));
            cities.add(new RomanizedLocation("黄冈", "huanggang"));
            cities.add(new RomanizedLocation("黄石", "huangshi"));
            cities.add(new RomanizedLocation("荆门", "jingmen"));
            cities.add(new RomanizedLocation("荆州", "jingzhou"));
            cities.add(new RomanizedLocation("潜江", "qianjiang"));
            cities.add(new RomanizedLocation("神农架林区", "shennongjialinqu"));
            cities.add(new RomanizedLocation("十堰", "shiyan"));
            cities.add(new RomanizedLocation("随州", "suizhou"));
            cities.add(new RomanizedLocation("天门", "tianmen"));
            cities.add(new RomanizedLocation("仙桃", "xiantao"));
            cities.add(new RomanizedLocation("咸宁", "xianning"));
            cities.add(new RomanizedLocation("襄阳", "xiangyang"));
            cities.add(new RomanizedLocation("孝感", "xiaogan"));
            cities.add(new RomanizedLocation("宜昌", "yichang"));
            cities.add(new RomanizedLocation("长沙", "changsha"));
            cities.add(new RomanizedLocation("常德", "changde"));
            cities.add(new RomanizedLocation("郴州", "chenzhou"));
            cities.add(new RomanizedLocation("衡阳", "hengyang"));
            cities.add(new RomanizedLocation("怀化", "huaihua"));
            cities.add(new RomanizedLocation("娄底", "loudi"));
            cities.add(new RomanizedLocation("邵阳", "shaoyang"));
            cities.add(new RomanizedLocation("湘潭", "xiangtan"));
            cities.add(new RomanizedLocation("湘西州", "xiangxizhou", "湘西土家族苗族自治州"));
            cities.add(new RomanizedLocation("益阳", "yiyang"));
            cities.add(new RomanizedLocation("永州", "yongzhou"));
            cities.add(new RomanizedLocation("岳阳", "yueyang"));
            cities.add(new RomanizedLocation("张家界", "zhangjiajie"));
            cities.add(new RomanizedLocation("株洲", "zhuzhou"));
            cities.add(new RomanizedLocation("南京", "nanjing"));
            cities.add(new RomanizedLocation("常州", "changzhou"));
            cities.add(new RomanizedLocation("淮安", "huaian"));
            cities.add(new RomanizedLocation("连云港", "lianyungang"));
            cities.add(new RomanizedLocation("南通", "nantong"));
            cities.add(new RomanizedLocation("苏州", "suzhou"));
            cities.add(new RomanizedLocation("宿迁", "suqian"));
            cities.add(new RomanizedLocation("泰州", "taizhou"));
            cities.add(new RomanizedLocation("无锡", "wuxi"));
            cities.add(new RomanizedLocation("徐州", "xuzhou"));
            cities.add(new RomanizedLocation("盐城", "yancheng"));
            cities.add(new RomanizedLocation("扬州", "yangzhou"));
            cities.add(new RomanizedLocation("镇江", "zhenjiang"));
            cities.add(new RomanizedLocation("南昌", "nanchang"));
            cities.add(new RomanizedLocation("抚州", "fuzhou"));
            cities.add(new RomanizedLocation("赣州", "ganzhou"));
            cities.add(new RomanizedLocation("吉安", "jian"));
            cities.add(new RomanizedLocation("景德镇", "jingdezhen"));
            cities.add(new RomanizedLocation("九江", "jiujiang"));
            cities.add(new RomanizedLocation("萍乡", "pingxiang"));
            cities.add(new RomanizedLocation("上饶", "shangrao"));
            cities.add(new RomanizedLocation("新余", "xinyu"));
            cities.add(new RomanizedLocation("宜春", "yichun"));
            cities.add(new RomanizedLocation("鹰潭", "yingtan"));
            cities.add(new RomanizedLocation("长春", "changchun"));
            cities.add(new RomanizedLocation("白城", "baicheng"));
            cities.add(new RomanizedLocation("白山", "baishan"));
            cities.add(new RomanizedLocation("吉林市", "jilinshi"));
            cities.add(new RomanizedLocation("辽源", "liaoyuan"));
            cities.add(new RomanizedLocation("四平", "siping"));
            cities.add(new RomanizedLocation("松原", "songyuan"));
            cities.add(new RomanizedLocation("通化", "tonghua"));
            cities.add(new RomanizedLocation("延边", "yanbian", "延边朝鲜族自治州"));
            cities.add(new RomanizedLocation("沈阳", "shenyang"));
            cities.add(new RomanizedLocation("鞍山", "anshan"));
            cities.add(new RomanizedLocation("本溪", "benxi"));
            cities.add(new RomanizedLocation("朝阳", "zhaoyang"));
            cities.add(new RomanizedLocation("大连", "dalian"));
            cities.add(new RomanizedLocation("丹东", "dandong"));
            cities.add(new RomanizedLocation("抚顺", "fushun"));
            cities.add(new RomanizedLocation("阜新", "fuxin"));
            cities.add(new RomanizedLocation("葫芦岛", "huludao"));
            cities.add(new RomanizedLocation("锦州", "jinzhou"));
            cities.add(new RomanizedLocation("辽阳", "liaoyang"));
            cities.add(new RomanizedLocation("盘锦", "panjin"));
            cities.add(new RomanizedLocation("铁岭", "tieling"));
            cities.add(new RomanizedLocation("营口", "yingkou"));
            cities.add(new RomanizedLocation("呼和浩特", "huhehaote"));
            cities.add(new RomanizedLocation("阿拉善盟", "alashanmeng"));
            cities.add(new RomanizedLocation("包头", "baotou"));
            cities.add(new RomanizedLocation("巴彦淖尔", "bayannaoer"));
            cities.add(new RomanizedLocation("赤峰", "chifeng"));
            cities.add(new RomanizedLocation("鄂尔多斯", "eerduosi"));
            cities.add(new RomanizedLocation("呼伦贝尔", "hulunbeier"));
            cities.add(new RomanizedLocation("通辽", "tongliao"));
            cities.add(new RomanizedLocation("乌海", "wuhai"));
            cities.add(new RomanizedLocation("乌兰察布", "wulanchabu"));
            cities.add(new RomanizedLocation("锡林郭勒盟", "xilinguolemeng"));
            cities.add(new RomanizedLocation("兴安盟", "xinganmeng"));
            cities.add(new RomanizedLocation("银川", "yinchuan"));
            cities.add(new RomanizedLocation("固原", "guyuan"));
            cities.add(new RomanizedLocation("石嘴山", "shizuishan"));
            cities.add(new RomanizedLocation("吴忠", "wuzhong"));
            cities.add(new RomanizedLocation("中卫", "zhongwei"));
            cities.add(new RomanizedLocation("西宁", "xining"));
            cities.add(new RomanizedLocation("果洛州", "guoluozhou", "果洛藏族自治州"));
            cities.add(new RomanizedLocation("海东市", "haidong"));
            cities.add(new RomanizedLocation("海北州", "haibeizhou", "海北藏族自治州"));
            cities.add(new RomanizedLocation("海南州", "hainanzhou", "海南藏族自治州"));
            cities.add(new RomanizedLocation("海西州", "haixizhou", "海西蒙古族藏族自治州"));
            cities.add(new RomanizedLocation("黄南州", "huangnanzhou", "黄南藏族自治州"));
            cities.add(new RomanizedLocation("玉树州", "yushuzhou", "玉树藏族自治州"));
            cities.add(new RomanizedLocation("济南", "jinan"));
            cities.add(new RomanizedLocation("滨州", "binzhou"));
            cities.add(new RomanizedLocation("东营", "dongying"));
            cities.add(new RomanizedLocation("德州", "dezhou"));
            cities.add(new RomanizedLocation("菏泽", "heze"));
            cities.add(new RomanizedLocation("济宁", "jining"));
            cities.add(new RomanizedLocation("莱芜", "laiwu"));
            cities.add(new RomanizedLocation("聊城", "liaocheng"));
            cities.add(new RomanizedLocation("临沂", "linyi"));
            cities.add(new RomanizedLocation("青岛", "qingdao"));
            cities.add(new RomanizedLocation("日照", "rizhao"));
            cities.add(new RomanizedLocation("泰安", "taian"));
            cities.add(new RomanizedLocation("威海", "weihai"));
            cities.add(new RomanizedLocation("潍坊", "weifang"));
            cities.add(new RomanizedLocation("烟台", "yantai"));
            cities.add(new RomanizedLocation("枣庄", "zaozhuang"));
            cities.add(new RomanizedLocation("淄博", "zibo"));
            cities.add(new RomanizedLocation("太原", "taiyuan"));
            cities.add(new RomanizedLocation("长治", "changzhi"));
            cities.add(new RomanizedLocation("大同", "datong"));
            cities.add(new RomanizedLocation("晋城", "jincheng"));
            cities.add(new RomanizedLocation("晋中", "jinzhong"));
            cities.add(new RomanizedLocation("临汾", "linfen"));
            cities.add(new RomanizedLocation("吕梁", "lvliang"));
            cities.add(new RomanizedLocation("朔州", "shuozhou"));
            cities.add(new RomanizedLocation("忻州", "xinzhou"));
            cities.add(new RomanizedLocation("阳泉", "yangquan"));
            cities.add(new RomanizedLocation("运城", "yuncheng"));
            cities.add(new RomanizedLocation("西安", "xian"));
            cities.add(new RomanizedLocation("安康", "ankang"));
            cities.add(new RomanizedLocation("宝鸡", "baoji"));
            cities.add(new RomanizedLocation("汉中", "hanzhong"));
            cities.add(new RomanizedLocation("商洛", "shangluo"));
            cities.add(new RomanizedLocation("铜川", "tongchuan"));
            cities.add(new RomanizedLocation("渭南", "weinan"));
            cities.add(new RomanizedLocation("咸阳", "xianyang"));
            cities.add(new RomanizedLocation("延安", "yanan"));
            cities.add(new RomanizedLocation("榆林", "yulin"));
            cities.add(new RomanizedLocation("成都", "chengdu"));
            cities.add(new RomanizedLocation("阿坝州", "abazhou", "阿坝藏族羌族自治州"));
            cities.add(new RomanizedLocation("巴中", "bazhong"));
            cities.add(new RomanizedLocation("达州", "dazhou"));
            cities.add(new RomanizedLocation("德阳", "deyang"));
            cities.add(new RomanizedLocation("甘孜州", "ganzizhou", "甘孜藏族自治州"));
            cities.add(new RomanizedLocation("广安", "guangan"));
            cities.add(new RomanizedLocation("广元", "guangyuan"));
            cities.add(new RomanizedLocation("乐山", "leshan"));
            cities.add(new RomanizedLocation("凉山州", "liangshanzhou", "凉山彝族自治州"));
            cities.add(new RomanizedLocation("泸州", "luzhou"));
            cities.add(new RomanizedLocation("南充", "nanchong"));
            cities.add(new RomanizedLocation("眉山", "meishan"));
            cities.add(new RomanizedLocation("绵阳", "mianyang"));
            cities.add(new RomanizedLocation("内江", "neijiang"));
            cities.add(new RomanizedLocation("攀枝花", "panzhihua"));
            cities.add(new RomanizedLocation("遂宁", "suining"));
            cities.add(new RomanizedLocation("雅安", "yaan"));
            cities.add(new RomanizedLocation("宜宾", "yibin"));
            cities.add(new RomanizedLocation("资阳", "ziyang"));
            cities.add(new RomanizedLocation("自贡", "zigong"));
            cities.add(new RomanizedLocation("拉萨", "lasa"));
            cities.add(new RomanizedLocation("阿里地区", "ali"));
            cities.add(new RomanizedLocation("昌都市", "changdu"));
            cities.add(new RomanizedLocation("林芝市", "linzhi"));
            cities.add(new RomanizedLocation("那曲地区", "naqu"));
            cities.add(new RomanizedLocation("日喀则市", "rikaze"));
            cities.add(new RomanizedLocation("山南地区", "shannan"));
            cities.add(new RomanizedLocation("乌鲁木齐", "wulumuqi"));
            cities.add(new RomanizedLocation("阿拉尔", "alaer"));
            cities.add(new RomanizedLocation("阿克苏地区", "akesu"));
            cities.add(new RomanizedLocation("阿勒泰地区", "aletai"));
            cities.add(new RomanizedLocation("巴音郭楞", "bayinguoleng", "巴音郭楞蒙古自治州"));
            cities.add(new RomanizedLocation("博尔塔拉州", "boertalazhou", "博尔塔拉蒙古自治州"));
            cities.add(new RomanizedLocation("昌吉州", "changjizhou", "昌吉回族自治州"));
            cities.add(new RomanizedLocation("哈密地区", "hami"));
            cities.add(new RomanizedLocation("和田地区", "hetian"));
            cities.add(new RomanizedLocation("喀什地区", "kashi"));
            cities.add(new RomanizedLocation("克拉玛依", "kelamayi"));
            cities.add(new RomanizedLocation("克孜勒苏州", "kezilesuzhou", "克孜勒苏柯尔克孜自治州"));
            cities.add(new RomanizedLocation("石河子", "shihezi"));
            cities.add(new RomanizedLocation("塔城地区", "tacheng"));
            cities.add(new RomanizedLocation("图木舒克", "tumushuke"));
            cities.add(new RomanizedLocation("吐鲁番地区", "tulufan"));
            cities.add(new RomanizedLocation("五家渠", "wujiaqu"));
            cities.add(new RomanizedLocation("伊犁州", "yilizhou", "伊犁哈萨克自治州"));
            cities.add(new RomanizedLocation("昆明", "kunming"));
            cities.add(new RomanizedLocation("保山", "baoshan"));
            cities.add(new RomanizedLocation("楚雄州", "chuxiongzhou", "楚雄彝族自治州"));
            cities.add(new RomanizedLocation("大理州", "dalizhou", "大理白族自治州"));
            cities.add(new RomanizedLocation("德宏州", "dehongzhou", "德宏傣族景颇族自治州"));
            cities.add(new RomanizedLocation("迪庆州", "diqingzhou", "迪庆藏族自治州"));
            cities.add(new RomanizedLocation("红河州", "honghezhou", "红河哈尼族彝族自治州"));
            cities.add(new RomanizedLocation("丽江", "lijiang"));
            cities.add(new RomanizedLocation("临沧", "lincang"));
            cities.add(new RomanizedLocation("怒江州", "nujiangzhou", "怒江傈僳族自治州"));
            cities.add(new RomanizedLocation("普洱", "puer"));
            cities.add(new RomanizedLocation("曲靖", "qujing"));
            cities.add(new RomanizedLocation("昭通", "zhaotong"));
            cities.add(new RomanizedLocation("文山", "wenshan", "文山壮族苗族自治州"));
            cities.add(new RomanizedLocation("西双版纳", "xishuangbanna", "西双版纳傣族自治州"));
            cities.add(new RomanizedLocation("玉溪", "yuxi"));
            cities.add(new RomanizedLocation("杭州", "hangzhou"));
            cities.add(new RomanizedLocation("湖州", "huzhou"));
            cities.add(new RomanizedLocation("嘉兴", "jiaxing"));
            cities.add(new RomanizedLocation("金华", "jinhua"));
            cities.add(new RomanizedLocation("丽水", "lishui"));
            cities.add(new RomanizedLocation("宁波", "ningbo"));
            cities.add(new RomanizedLocation("衢州", "quzhou"));
            cities.add(new RomanizedLocation("绍兴", "shaoxing"));
            cities.add(new RomanizedLocation("台州", "taizhou"));
            cities.add(new RomanizedLocation("温州", "wenzhou"));
            cities.add(new RomanizedLocation("舟山", "zhoushan"));
            cities.add(new RomanizedLocation("香港", "xianggang"));
            cities.add(new RomanizedLocation("澳门", "aomen"));
            cities.add(new RomanizedLocation("北京", "beijing"));
            cities.add(new RomanizedLocation("上海", "shanghai"));
            cities.add(new RomanizedLocation("天津", "tianjin"));
            cities.add(new RomanizedLocation("重庆", "chongqing"));
            cities.add(new RomanizedLocation("台北", "taibei"));
            cities.add(new RomanizedLocation("高雄", "gaoxiong"));
            cities.add(new RomanizedLocation("台中", "taizhong"));
            cities.add(new RomanizedLocation("台南", "tainan"));
            cities.add(new RomanizedLocation("新北", "xinbei"));
            cities.add(new RomanizedLocation("基隆", "jilong"));
            cities.add(new RomanizedLocation("新竹", "xinzhu"));
            cities.add(new RomanizedLocation("嘉义", "jiayi"));
            Collections.sort(cities);
        }
        return new ArrayList<>(cities);
    }
}